### PR TITLE
Adding feedback

### PR DESCRIPTION
**Pull request by YerkoPalma**
- https://github.com/sindresorhus/awesome/pull/816

**Don't merge yet**

### CODE REVIEW

**Comment by YerkoPalma** [comment]
@ungoldman As you can see, I'm following Sindre feedback to add this list to the awesome list.  Now, there are some things that I can't resolve right now, so I would really appreciate some help, specially with the **community links** and **youtube videos and talks** (I have many of those sites blocked right now :P)

**Comment by ungoldman** [comment]
Hi @YerkoPalma! Thanks for doing this. I will try to take a look and help out later today.

**Comment by ungoldman** [comment]
Hello again @YerkoPalma, I've added community resources, demos, and videos. Please feel free to merge when you think this is ready. Sorry it took me a while to get back to you. Hope this helps!

**Comment by YerkoPalma** [comment]
I think we are good to go :+1:  
Thanks

**Pull request merged**
